Update readme.
upb-uc4/hlf-network pull request #105
Opened 2020-11-18 09:44 UTC by palkra

Closes #88

2020-11-25 16:01 UTC, dhelmert requested changes

2020-11-26 12:28 UTC, dhelmert approved these changes

2020-11-27 15:01 UTC, anemonekk approved these changes

2020-11-27 16:02 UTC, this-kramer commented on README.md
I would argue that this rather belongs to the API repo, since we should not care about how the API is tested. But we can add it if you want to :)

2020-11-30 10:18 UTC, merged