Feature/hyperledger version secret
upb-uc4/hlf-network pull request #110
Opened 2021-01-04 18:40 UTC by this-kramer

## Reason for this PR:
  - We display the version of all components in the uc4 frontend.
  - There is no endpoint for the hlf-network version.

## Changes in this PR:
 - Add environment variable for version to `env.sh`
 - Write version to secret for uc4-lagom namespace

2021-01-04 19:13 UTC, david-buderus requested changes

2021-01-04 19:13 UTC, david-buderus commented on scripts/env.sh
> +export HL_PRODUCTION_NETWORK_VERSION="v0.13.0"
Isn't the version v0.16.0?

2021-01-04 19:47 UTC, this-kramer commented on scripts/env.sh
> +export HL_PRODUCTION_NETWORK_VERSION="v0.13.0"
Oh good catch, I thought about the last release but we will never release this as v0.13.0... 😅

2021-01-05 10:42 UTC, david-buderus approved these changes

2021-01-05 10:43 UTC, merged